apiKey: dcd0e10112e5db6f9b3336668e27f3
artifactDirectory: null
clusterId: null
command: "python helloworld.py"
container: python:3.8
containerUser: null
experimentEnv: null
ignoreFiles: null
isPreemptible: false
machineType: C7
modelPath: null
modelType: null
name: Hello
no-logs: false
ports: null
projectId: prlufwnqu
registryPassword: null
registryUrl: null
registryUsername: null
tag: null
tags: null
tensorboard: false
tensorboard_set: null
workingDirectory: null
workspace: "."
datasetUri: s3://s3.us-east-2.wasabisys.com
datasetName: tear-film-summer-2020
datasetAwsAccessKeyId: 5KBROCCWF9BLWFEURFHG
datasetAwsSecretAccessKey: v4gIdzhNQu0py4XJ5berlyME0Ee4PnPX8QUMwd1m
